
  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shellh
      - name: make all files accessible
        run: sudo chmod -R 777 /root/actions-runner
        
      - name: Remove the present directory as git will give error
        run: sudo rm -rf /opt/lampp/htdocs/ems/

      # Runs a set of commands using the runners shell
      - name: Fetch the Code 
        run: sudo git clone https://github.com/ParthTagalpallewar/ems.git /opt/lampp/htdocs/ems
        
      - name: Cd to ems
        run:  cd /opt/lampp/htdocs
        
      - name: Make file accessible to all users
        run: sudo chmod -R 777 /opt/lampp/htdocs ems/
        
      - name: Cd to ems
        run:  cd /opt/lampp/htdocs ems
        
      - name: Install all dependencies
        run: sudo composer install 